'use strict';

module.exports = [
  {
    name: 'Science',
    icon: '🔬',
    color: '#00B894',
    description: 'Physics, chemistry, biology and the natural world',
    questions: [
      { difficulty: 'easy', question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Mercury'], answerIndex: 1, explanation: 'Mars looks red because of iron oxide (rust) on its surface.' },
      { difficulty: 'easy', question: 'What is H2O commonly known as?', options: ['Oxygen', 'Hydrogen', 'Water', 'Helium'], answerIndex: 2, explanation: 'H2O is the chemical formula for water: two hydrogen atoms and one oxygen atom.' },
      { difficulty: 'easy', question: 'How many legs does a spider have?', options: ['Six', 'Eight', 'Ten', 'Four'], answerIndex: 1, explanation: 'Spiders are arachnids, which have eight legs.' },
      { difficulty: 'easy', question: 'Which gas do plants absorb from the atmosphere for photosynthesis?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answerIndex: 2, explanation: 'Plants take in carbon dioxide and release oxygen during photosynthesis.' },
      { difficulty: 'easy', question: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], answerIndex: 2, explanation: 'Diamond scores 10 on the Mohs hardness scale, the highest of any natural material.' },
      { difficulty: 'easy', question: 'Which organ pumps blood around the human body?', options: ['Liver', 'Heart', 'Kidney', 'Lung'], answerIndex: 1, explanation: 'The heart is a muscular organ that pumps blood through the circulatory system.' },
      { difficulty: 'easy', question: 'What force pulls objects toward the Earth?', options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], answerIndex: 2, explanation: 'Gravity is the attractive force between masses, pulling objects toward Earth.' },
      { difficulty: 'medium', question: 'What is the chemical symbol for gold?', options: ['Ag', 'Au', 'Gd', 'Go'], answerIndex: 1, explanation: 'Au comes from "aurum", the Latin word for gold.' },
      { difficulty: 'medium', question: 'Which planet has the most confirmed moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answerIndex: 1, explanation: 'Saturn has 146 confirmed moons, more than any other planet.' },
      { difficulty: 'medium', question: 'Which part of the cell contains most of its DNA?', options: ['Ribosome', 'Nucleus', 'Mitochondria', 'Cytoplasm'], answerIndex: 1, explanation: 'The nucleus stores the cell\'s genetic material as chromosomes.' },
      { difficulty: 'medium', question: 'Approximately what is the speed of light in a vacuum?', options: ['150,000 km/s', '300,000 km/s', '1,000,000 km/s', '30,000 km/s'], answerIndex: 1, explanation: 'Light travels at about 299,792 km per second in a vacuum.' },
      { difficulty: 'medium', question: 'Which blood cells carry oxygen around the body?', options: ['White blood cells', 'Platelets', 'Red blood cells', 'Plasma cells'], answerIndex: 2, explanation: 'Red blood cells contain hemoglobin, which binds and transports oxygen.' },
      { difficulty: 'medium', question: 'What is the most abundant gas in Earth\'s atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'], answerIndex: 2, explanation: 'Nitrogen makes up about 78% of Earth\'s atmosphere.' },
      { difficulty: 'medium', question: 'How many bones are in the adult human body?', options: ['186', '206', '226', '256'], answerIndex: 1, explanation: 'Adults have 206 bones; babies are born with around 300, some of which fuse.' },
      { difficulty: 'hard', question: 'Which subatomic particle is nicknamed the "God particle"?', options: ['Photon', 'Higgs boson', 'Gluon', 'Neutrino'], answerIndex: 1, explanation: 'The Higgs boson gives other particles mass and was confirmed at CERN in 2012.' },
      { difficulty: 'hard', question: 'Which element has the highest electronegativity?', options: ['Oxygen', 'Fluorine', 'Chlorine', 'Nitrogen'], answerIndex: 1, explanation: 'Fluorine is the most electronegative element on the Pauling scale (3.98).' },
      { difficulty: 'hard', question: 'Approximately how old is the universe?', options: ['10.2 billion years', '13.8 billion years', '16.5 billion years', '20.1 billion years'], answerIndex: 1, explanation: 'Measurements of the cosmic microwave background date the Big Bang to about 13.8 billion years ago.' },
      { difficulty: 'hard', question: 'Which law states that energy cannot be created or destroyed?', options: ['Newton\'s third law', 'First law of thermodynamics', 'Boyle\'s law', 'Ohm\'s law'], answerIndex: 1, explanation: 'The first law of thermodynamics is the law of conservation of energy.' },
      { difficulty: 'hard', question: 'What is the pH of pure water at 25°C?', options: ['0', '7', '14', '1'], answerIndex: 1, explanation: 'Pure water is neutral with a pH of 7 at 25°C.' },
      { difficulty: 'hard', question: 'Which scientist proposed the theory of continental drift?', options: ['Charles Darwin', 'Alfred Wegener', 'Gregor Mendel', 'Louis Pasteur'], answerIndex: 1, explanation: 'Alfred Wegener proposed continental drift in 1912, a precursor to plate tectonics.' },
    ],
  },
  {
    name: 'Sports',
    icon: '⚽',
    color: '#E17055',
    description: 'Football, cricket, Olympics and more',
    questions: [
      { difficulty: 'easy', question: 'How many players does a football (soccer) team field at a time?', options: ['9', '10', '11', '12'], answerIndex: 2, explanation: 'A football team fields 11 players, including the goalkeeper.' },
      { difficulty: 'easy', question: 'In which sport does the term "love" mean a score of zero?', options: ['Badminton', 'Tennis', 'Squash', 'Golf'], answerIndex: 1, explanation: 'In tennis, "love" means zero — possibly from the French "l\'oeuf" (egg).' },
      { difficulty: 'easy', question: 'How many rings are on the Olympic flag?', options: ['Four', 'Five', 'Six', 'Seven'], answerIndex: 1, explanation: 'The five rings represent the five inhabited continents.' },
      { difficulty: 'easy', question: 'Which sport is played with a puck?', options: ['Basketball', 'Ice hockey', 'Baseball', 'Rugby'], answerIndex: 1, explanation: 'Ice hockey is played with a hard rubber puck.' },
      { difficulty: 'easy', question: 'In basketball, how many points is a free throw worth?', options: ['One', 'Two', 'Three', 'Four'], answerIndex: 0, explanation: 'Each successful free throw scores one point.' },
      { difficulty: 'easy', question: 'What is a "birdie" in golf?', options: ['One stroke under par', 'One stroke over par', 'Two strokes under par', 'A hole in one'], answerIndex: 0, explanation: 'A birdie is completing a hole one stroke under par.' },
      { difficulty: 'easy', question: 'In which country did table tennis originate?', options: ['China', 'England', 'Japan', 'South Korea'], answerIndex: 1, explanation: 'Table tennis began in Victorian England as an indoor version of tennis.' },
      { difficulty: 'medium', question: 'How often are the Summer Olympic Games held?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], answerIndex: 2, explanation: 'The Summer Olympics follow a four-year cycle called an Olympiad.' },
      { difficulty: 'medium', question: 'In cricket, how many legal balls are bowled in one over?', options: ['Five', 'Six', 'Eight', 'Ten'], answerIndex: 1, explanation: 'A standard over consists of six legal deliveries.' },
      { difficulty: 'medium', question: 'Which boxer was known as "The Greatest"?', options: ['Mike Tyson', 'Muhammad Ali', 'Joe Frazier', 'Rocky Marciano'], answerIndex: 1, explanation: 'Muhammad Ali called himself "The Greatest" and is widely regarded as such.' },
      { difficulty: 'medium', question: 'How long is an official marathon?', options: ['40 km', '42.195 km', '45 km', '50 km'], answerIndex: 1, explanation: 'The marathon distance was standardized at 42.195 km at the 1908 London Olympics.' },
      { difficulty: 'medium', question: 'In which city were the first modern Olympic Games held in 1896?', options: ['Paris', 'Athens', 'London', 'Rome'], answerIndex: 1, explanation: 'Athens hosted the first modern Olympics in 1896.' },
      { difficulty: 'medium', question: 'What does FIFA stand for?', options: ['Federation of International Football Associations', 'Fédération Internationale de Football Association', 'Football International Federation Alliance', 'Federation for International Football Advancement'], answerIndex: 1, explanation: 'FIFA is the French acronym for the International Federation of Association Football.' },
      { difficulty: 'medium', question: 'How many holes are played in a standard round of golf?', options: ['9', '12', '18', '24'], answerIndex: 2, explanation: 'A full round of golf is 18 holes.' },
      { difficulty: 'hard', question: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Brazil', 'Italy', 'Argentina'], answerIndex: 1, explanation: 'Brazil has won five World Cups: 1958, 1962, 1970, 1994 and 2002.' },
      { difficulty: 'hard', question: 'In tennis, what is a "bagel"?', options: ['Winning a set 6-0', 'A type of serve', 'A tiebreak decider', 'A double fault'], answerIndex: 0, explanation: 'A 6-0 set looks like a bagel (zero), hence the nickname.' },
      { difficulty: 'hard', question: 'Who holds the men\'s 100m sprint world record?', options: ['Tyson Gay', 'Usain Bolt', 'Yohan Blake', 'Asafa Powell'], answerIndex: 1, explanation: 'Usain Bolt ran 9.58 seconds in Berlin in 2009.' },
      { difficulty: 'hard', question: 'In chess, which piece can only move diagonally?', options: ['Rook', 'Knight', 'Bishop', 'Queen'], answerIndex: 2, explanation: 'The bishop moves any number of squares diagonally.' },
      { difficulty: 'hard', question: 'In which year were women first allowed to compete in the modern Olympics?', options: ['1896', '1900', '1908', '1924'], answerIndex: 1, explanation: 'Women first competed at the Paris 1900 Games.' },
      { difficulty: 'hard', question: 'What is the maximum possible break in snooker?', options: ['120', '135', '147', '155'], answerIndex: 2, explanation: 'A 147 is 15 reds with 15 blacks followed by all the colours.' },
    ],
  },
  {
    name: 'History',
    icon: '🏛️',
    color: '#FDCB6E',
    description: 'Civilizations, wars and world-changing events',
    questions: [
      { difficulty: 'easy', question: 'Which famous ship sank on its maiden voyage in 1912?', options: ['Lusitania', 'Titanic', 'Britannic', 'Queen Mary'], answerIndex: 1, explanation: 'The Titanic struck an iceberg and sank in April 1912.' },
      { difficulty: 'easy', question: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams'], answerIndex: 1, explanation: 'George Washington took office in 1789.' },
      { difficulty: 'easy', question: 'In which year did World War II end?', options: ['1939', '1943', '1945', '1950'], answerIndex: 2, explanation: 'The war in Europe ended in May 1945 and in the Pacific in September 1945.' },
      { difficulty: 'easy', question: 'The Great Wall is located in which country?', options: ['India', 'China', 'Egypt', 'Peru'], answerIndex: 1, explanation: 'The Great Wall of China stretches over 21,000 km.' },
      { difficulty: 'easy', question: 'Who painted the Mona Lisa?', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo'], answerIndex: 2, explanation: 'Leonardo da Vinci painted it in the early 1500s.' },
      { difficulty: 'easy', question: 'Which ancient civilization built the pyramids of Giza?', options: ['Romans', 'Greeks', 'Egyptians', 'Mayans'], answerIndex: 2, explanation: 'The Giza pyramids were built as tombs for Egyptian pharaohs around 2600–2500 BCE.' },
      { difficulty: 'easy', question: 'What language was spoken in the Roman Empire?', options: ['Greek', 'Latin', 'Italian', 'French'], answerIndex: 1, explanation: 'Latin was the official language of Rome and the root of the Romance languages.' },
      { difficulty: 'medium', question: 'In which year did India gain independence?', options: ['1945', '1947', '1950', '1952'], answerIndex: 1, explanation: 'India became independent on 15 August 1947.' },
      { difficulty: 'medium', question: 'Who was the British Prime Minister for most of World War II?', options: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], answerIndex: 1, explanation: 'Churchill led Britain from 1940 to 1945.' },
      { difficulty: 'medium', question: 'The Renaissance began in which European country?', options: ['France', 'England', 'Italy', 'Spain'], answerIndex: 2, explanation: 'The Renaissance started in the Italian city-states in the 14th century.' },
      { difficulty: 'medium', question: 'Which empire was founded by Genghis Khan?', options: ['Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'Mughal Empire'], answerIndex: 1, explanation: 'Genghis Khan united the Mongol tribes and founded the Mongol Empire in 1206.' },
      { difficulty: 'medium', question: 'In which year did the Berlin Wall fall?', options: ['1985', '1987', '1989', '1991'], answerIndex: 2, explanation: 'The wall fell on 9 November 1989.' },
      { difficulty: 'medium', question: 'Who delivered the "I Have a Dream" speech in 1963?', options: ['Malcolm X', 'Martin Luther King Jr.', 'Rosa Parks', 'Nelson Mandela'], answerIndex: 1, explanation: 'King delivered it during the March on Washington.' },
      { difficulty: 'medium', question: 'The concept of zero as a number is credited to mathematicians of which civilization?', options: ['Greece', 'Egypt', 'India', 'China'], answerIndex: 2, explanation: 'Indian mathematician Brahmagupta formalized zero\'s rules in the 7th century.' },
      { difficulty: 'hard', question: 'In which year did Constantinople fall, ending the Byzantine Empire?', options: ['1204', '1347', '1453', '1517'], answerIndex: 2, explanation: 'Ottoman forces captured the city in 1453.' },
      { difficulty: 'hard', question: 'Who was the first emperor of a unified China?', options: ['Kublai Khan', 'Qin Shi Huang', 'Wu of Han', 'Taizong of Tang'], answerIndex: 1, explanation: 'Qin Shi Huang unified China in 221 BCE and began the Great Wall.' },
      { difficulty: 'hard', question: 'The Treaty of Versailles was signed in which year?', options: ['1918', '1919', '1920', '1921'], answerIndex: 1, explanation: 'It was signed on 28 June 1919, formally ending World War I.' },
      { difficulty: 'hard', question: 'Which pharaoh\'s nearly intact tomb was discovered in 1922?', options: ['Ramses II', 'Tutankhamun', 'Khufu', 'Akhenaten'], answerIndex: 1, explanation: 'Howard Carter discovered Tutankhamun\'s tomb in the Valley of the Kings.' },
      { difficulty: 'hard', question: 'The 1884–85 conference that formalized the "Scramble for Africa" was held in which city?', options: ['London', 'Paris', 'Berlin', 'Brussels'], answerIndex: 2, explanation: 'The Berlin Conference regulated European colonization of Africa.' },
      { difficulty: 'hard', question: 'Who was the last Viceroy of India?', options: ['Lord Curzon', 'Lord Mountbatten', 'Lord Irwin', 'Lord Wavell'], answerIndex: 1, explanation: 'Lord Mountbatten oversaw the transfer of power in 1947.' },
    ],
  },
  {
    name: 'Technology',
    icon: '💻',
    color: '#0984E3',
    description: 'Computers, internet and modern tech',
    questions: [
      { difficulty: 'easy', question: 'What does "CPU" stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Utility'], answerIndex: 0, explanation: 'The CPU is the primary chip that executes instructions.' },
      { difficulty: 'easy', question: 'Which company created the iPhone?', options: ['Samsung', 'Apple', 'Google', 'Nokia'], answerIndex: 1, explanation: 'Apple launched the first iPhone in 2007.' },
      { difficulty: 'easy', question: 'What does "www" stand for in a web address?', options: ['World Wide Web', 'Web World Wide', 'World Web Window', 'Wide World Web'], answerIndex: 0, explanation: 'WWW stands for World Wide Web.' },
      { difficulty: 'easy', question: 'Which device is primarily used to type on a computer?', options: ['Mouse', 'Monitor', 'Keyboard', 'Speaker'], answerIndex: 2, explanation: 'The keyboard is the main text-input device.' },
      { difficulty: 'easy', question: 'What is the name of Google\'s mobile operating system?', options: ['iOS', 'Windows Phone', 'Android', 'HarmonyOS'], answerIndex: 2, explanation: 'Android is developed by Google and powers most smartphones worldwide.' },
      { difficulty: 'easy', question: 'What does "USB" stand for?', options: ['Universal Serial Bus', 'United System Board', 'Universal Service Button', 'Ultra Speed Bandwidth'], answerIndex: 0, explanation: 'USB stands for Universal Serial Bus.' },
      { difficulty: 'easy', question: 'Which company developed the Windows operating system?', options: ['Apple', 'IBM', 'Microsoft', 'Oracle'], answerIndex: 2, explanation: 'Microsoft released Windows 1.0 in 1985.' },
      { difficulty: 'medium', question: 'Who co-founded Apple Computer with Steve Jobs?', options: ['Bill Gates', 'Steve Wozniak', 'Larry Page', 'Elon Musk'], answerIndex: 1, explanation: 'Steve Wozniak designed the Apple I and Apple II.' },
      { difficulty: 'medium', question: 'What does "AI" stand for?', options: ['Automated Interface', 'Artificial Intelligence', 'Advanced Internet', 'Analog Input'], answerIndex: 1, explanation: 'AI stands for Artificial Intelligence.' },
      { difficulty: 'medium', question: 'Which programming language is most popular for data science and AI?', options: ['Python', 'C++', 'Java', 'PHP'], answerIndex: 0, explanation: 'Python dominates data science thanks to libraries like NumPy and TensorFlow.' },
      { difficulty: 'medium', question: 'In which year was the first iPhone released?', options: ['2005', '2007', '2009', '2010'], answerIndex: 1, explanation: 'Steve Jobs unveiled the iPhone in January 2007.' },
      { difficulty: 'medium', question: 'What does "HTTP" stand for?', options: ['HyperText Transfer Protocol', 'High Transfer Text Process', 'Hyperlink Text Transmission Program', 'Host Transfer Text Protocol'], answerIndex: 0, explanation: 'HTTP is the foundation protocol of the World Wide Web.' },
      { difficulty: 'medium', question: 'Which company owns YouTube?', options: ['Meta', 'Amazon', 'Google', 'Microsoft'], answerIndex: 2, explanation: 'Google acquired YouTube in 2006.' },
      { difficulty: 'medium', question: 'How many bits are in a single byte?', options: ['4', '8', '16', '32'], answerIndex: 1, explanation: 'A byte is 8 bits by standard definition.' },
      { difficulty: 'hard', question: 'Who is considered the inventor of the World Wide Web?', options: ['Vint Cerf', 'Tim Berners-Lee', 'Bill Gates', 'Linus Torvalds'], answerIndex: 1, explanation: 'Tim Berners-Lee proposed the Web in 1989 at CERN.' },
      { difficulty: 'hard', question: 'What does "SQL" stand for?', options: ['Simple Query Language', 'Structured Query Language', 'Standard Question Logic', 'System Query Link'], answerIndex: 1, explanation: 'SQL is the standard language for relational databases.' },
      { difficulty: 'hard', question: 'Which encryption standard replaced DES?', options: ['RSA', 'AES', 'MD5', 'SHA-1'], answerIndex: 1, explanation: 'The Advanced Encryption Standard (AES) was adopted in 2001.' },
      { difficulty: 'hard', question: 'In which year was the Bitcoin whitepaper published?', options: ['2006', '2008', '2010', '2012'], answerIndex: 1, explanation: 'Satoshi Nakamoto published it on 31 October 2008.' },
      { difficulty: 'hard', question: 'What is the time complexity of binary search on a sorted array?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], answerIndex: 1, explanation: 'Binary search halves the search space each step: O(log n).' },
      { difficulty: 'hard', question: 'Which research lab developed the first working transistor in 1947?', options: ['Xerox PARC', 'Bell Labs', 'IBM Research', 'MIT Lincoln Lab'], answerIndex: 1, explanation: 'Bardeen, Brattain and Shockley built it at Bell Labs.' },
    ],
  },
  {
    name: 'Geography',
    icon: '🌍',
    color: '#00CEC9',
    description: 'Countries, capitals, rivers and wonders',
    questions: [
      { difficulty: 'easy', question: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answerIndex: 2, explanation: 'The Pacific covers about one-third of Earth\'s surface.' },
      { difficulty: 'easy', question: 'On which continent is the Sahara Desert located?', options: ['Asia', 'Africa', 'Australia', 'South America'], answerIndex: 1, explanation: 'The Sahara spans North Africa.' },
      { difficulty: 'easy', question: 'What is the capital of France?', options: ['Lyon', 'Marseille', 'Paris', 'Nice'], answerIndex: 2, explanation: 'Paris has been France\'s capital for centuries.' },
      { difficulty: 'easy', question: 'Which is the smallest continent by land area?', options: ['Europe', 'Antarctica', 'Australia', 'South America'], answerIndex: 2, explanation: 'Australia is the smallest continent.' },
      { difficulty: 'easy', question: 'Mount Everest sits on the border of Nepal and which country?', options: ['India', 'Bhutan', 'China', 'Pakistan'], answerIndex: 2, explanation: 'Everest straddles Nepal and Tibet (China).' },
      { difficulty: 'easy', question: 'What is the capital of Japan?', options: ['Kyoto', 'Osaka', 'Tokyo', 'Hiroshima'], answerIndex: 2, explanation: 'Tokyo is Japan\'s capital and largest city.' },
      { difficulty: 'easy', question: 'Which sea borders India to the west?', options: ['Bay of Bengal', 'Arabian Sea', 'Red Sea', 'Andaman Sea'], answerIndex: 1, explanation: 'The Arabian Sea lies west of India\'s coast.' },
      { difficulty: 'medium', question: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answerIndex: 2, explanation: 'Canberra is the purpose-built capital — not Sydney!' },
      { difficulty: 'medium', question: 'Which country has the largest population in the world?', options: ['China', 'India', 'United States', 'Indonesia'], answerIndex: 1, explanation: 'India overtook China as the most populous country in 2023.' },
      { difficulty: 'medium', question: 'The Amazon rainforest is mostly located in which country?', options: ['Peru', 'Colombia', 'Brazil', 'Venezuela'], answerIndex: 2, explanation: 'About 60% of the Amazon lies within Brazil.' },
      { difficulty: 'medium', question: 'Which strait separates Spain from Morocco?', options: ['Strait of Messina', 'Strait of Gibraltar', 'Bosphorus', 'Strait of Hormuz'], answerIndex: 1, explanation: 'The Strait of Gibraltar links the Atlantic and Mediterranean.' },
      { difficulty: 'medium', question: 'What is the deepest point in the world\'s oceans?', options: ['Puerto Rico Trench', 'Mariana Trench', 'Java Trench', 'Tonga Trench'], answerIndex: 1, explanation: 'The Mariana Trench\'s Challenger Deep is about 10,900 m deep.' },
      { difficulty: 'medium', question: 'Which African country was formerly known as Abyssinia?', options: ['Somalia', 'Ethiopia', 'Eritrea', 'Sudan'], answerIndex: 1, explanation: 'Ethiopia was historically called Abyssinia.' },
      { difficulty: 'medium', question: 'Which is the longest river in Europe?', options: ['Danube', 'Rhine', 'Volga', 'Seine'], answerIndex: 2, explanation: 'The Volga runs about 3,530 km through Russia.' },
      { difficulty: 'hard', question: 'What is the capital of Kazakhstan?', options: ['Almaty', 'Astana', 'Tashkent', 'Bishkek'], answerIndex: 1, explanation: 'Astana (renamed several times) is the capital.' },
      { difficulty: 'hard', question: 'Which country spans the most time zones?', options: ['Russia', 'United States', 'France', 'China'], answerIndex: 2, explanation: 'France has 12–13 time zones thanks to its overseas territories.' },
      { difficulty: 'hard', question: 'The "Ring of Fire" volcanic belt circles which ocean?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answerIndex: 2, explanation: 'The Pacific Ring of Fire hosts most of Earth\'s volcanoes and earthquakes.' },
      { difficulty: 'hard', question: 'Which is the driest non-polar desert on Earth?', options: ['Sahara', 'Gobi', 'Atacama', 'Kalahari'], answerIndex: 2, explanation: 'Chile\'s Atacama Desert can go years without rain.' },
      { difficulty: 'hard', question: 'Lesotho is a country entirely surrounded by which nation?', options: ['Namibia', 'South Africa', 'Botswana', 'Zimbabwe'], answerIndex: 1, explanation: 'Lesotho is an enclave within South Africa.' },
      { difficulty: 'hard', question: 'Which country is also a continent?', options: ['Brazil', 'Australia', 'India', 'Canada'], answerIndex: 1, explanation: 'Australia is both a country and a continent.' },
    ],
  },
  {
    name: 'Entertainment',
    icon: '🎬',
    color: '#E84393',
    description: 'Movies, music and pop culture',
    questions: [
      { difficulty: 'easy', question: 'Who directed the 1997 film "Titanic"?', options: ['Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Ridley Scott'], answerIndex: 1, explanation: 'James Cameron directed and co-wrote Titanic.' },
      { difficulty: 'easy', question: 'Which band performed "Bohemian Rhapsody"?', options: ['The Beatles', 'Queen', 'ABBA', 'Led Zeppelin'], answerIndex: 1, explanation: 'Queen released it in 1975, written by Freddie Mercury.' },
      { difficulty: 'easy', question: 'What is the cowboy\'s name in "Toy Story"?', options: ['Buzz', 'Woody', 'Jessie', 'Rex'], answerIndex: 1, explanation: 'Woody is the pull-string cowboy doll.' },
      { difficulty: 'easy', question: 'Which singer is known as the "King of Pop"?', options: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], answerIndex: 1, explanation: 'Michael Jackson earned the title with "Thriller", the best-selling album ever.' },
      { difficulty: 'easy', question: 'How many films are in the original "Jurassic Park" trilogy?', options: ['Two', 'Three', 'Four', 'Five'], answerIndex: 1, explanation: 'The original trilogy ran from 1993 to 2001.' },
      { difficulty: 'easy', question: 'Which instrument has 88 keys?', options: ['Guitar', 'Violin', 'Piano', 'Flute'], answerIndex: 2, explanation: 'A standard piano has 52 white and 36 black keys.' },
      { difficulty: 'easy', question: 'Which streaming service produced "Stranger Things"?', options: ['Hulu', 'Disney+', 'Netflix', 'Amazon Prime'], answerIndex: 2, explanation: 'Netflix released the first season in 2016.' },
      { difficulty: 'medium', question: 'Who played Jack Dawson in "Titanic"?', options: ['Brad Pitt', 'Leonardo DiCaprio', 'Matt Damon', 'Tom Cruise'], answerIndex: 1, explanation: 'Leonardo DiCaprio starred opposite Kate Winslet.' },
      { difficulty: 'medium', question: 'Which film won the first Academy Award for Best Picture in 1929?', options: ['Sunrise', 'Wings', 'Metropolis', 'The Jazz Singer'], answerIndex: 1, explanation: 'The WWI epic "Wings" won at the first Oscars ceremony.' },
      { difficulty: 'medium', question: 'Who wrote the "Harry Potter" book series?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'Roald Dahl', 'C.S. Lewis'], answerIndex: 1, explanation: 'J.K. Rowling published seven Harry Potter novels.' },
      { difficulty: 'medium', question: 'Which artist released the album "Thriller" in 1982?', options: ['Prince', 'Madonna', 'Michael Jackson', 'Whitney Houston'], answerIndex: 2, explanation: '"Thriller" remains the best-selling album of all time.' },
      { difficulty: 'medium', question: 'In which year was the first "Star Wars" film released?', options: ['1975', '1977', '1980', '1983'], answerIndex: 1, explanation: '"Star Wars" (later "A New Hope") premiered in 1977.' },
      { difficulty: 'medium', question: 'Who created the animated series "The Simpsons"?', options: ['Seth MacFarlane', 'Matt Groening', 'Trey Parker', 'Mike Judge'], answerIndex: 1, explanation: 'Matt Groening created the show, debuting in 1989.' },
      { difficulty: 'medium', question: 'Which film features the line "Here\'s looking at you, kid"?', options: ['Gone with the Wind', 'Casablanca', 'Citizen Kane', 'It\'s a Wonderful Life'], answerIndex: 1, explanation: 'Humphrey Bogart says it in "Casablanca" (1942).' },
      { difficulty: 'hard', question: 'Who composed the score for "Interstellar" (2014)?', options: ['John Williams', 'Hans Zimmer', 'Ennio Morricone', 'Danny Elfman'], answerIndex: 1, explanation: 'Hans Zimmer\'s organ-driven score is iconic.' },
      { difficulty: 'hard', question: 'Which actor has won the most Academy Awards for acting?', options: ['Meryl Streep', 'Katharine Hepburn', 'Jack Nicholson', 'Daniel Day-Lewis'], answerIndex: 1, explanation: 'Katharine Hepburn won four Best Actress Oscars.' },
      { difficulty: 'hard', question: 'What was the first feature-length animated film?', options: ['Fantasia', 'Snow White and the Seven Dwarfs', 'Pinocchio', 'Bambi'], answerIndex: 1, explanation: 'Disney\'s "Snow White" premiered in 1937.' },
      { difficulty: 'hard', question: 'Which film is the highest-grossing movie of all time (unadjusted)?', options: ['Avengers: Endgame', 'Avatar', 'Titanic', 'Jurassic World'], answerIndex: 1, explanation: 'James Cameron\'s "Avatar" (2009) tops the global box office.' },
      { difficulty: 'hard', question: 'Who wrote the novel "Dune"?', options: ['Isaac Asimov', 'Arthur C. Clarke', 'Frank Herbert', 'Philip K. Dick'], answerIndex: 2, explanation: 'Frank Herbert published "Dune" in 1965.' },
      { difficulty: 'hard', question: 'Which 1927 film was the first "talkie" with synchronized dialogue?', options: ['Metropolis', 'The Jazz Singer', 'City Lights', 'Sunrise'], answerIndex: 1, explanation: '"The Jazz Singer" launched the sound era of cinema.' },
    ],
  },
];
